spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/correspondencia
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # You can set this to "update" or "none" based on your needs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect